// 'use client'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import StyledComponentsRegistry from './lib/registry'
import { AnimatePresence } from 'framer-motion'
import { usePathname } from 'next/navigation'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({

  children,
}: {
  children: React.ReactNode
}) {
  const pathName = usePathname();
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="/style.css" />
      </head>
      <body className={inter.className}>
      <StyledComponentsRegistry>
        <>
      {
        pathName!=='/profile'? 
        <h1 style={{width:"100vw",textAlign:"center",fontSize:24}}>Nextjs</h1>
        :""
      }
        {children}
        </>
        </StyledComponentsRegistry>        
      </body>
    </html>
  )
}
